---
# file: roles/horizon/tasks/config.yml
- name: Set Horizon configuration
  lineinfile:
    dest=/etc/openstack-dashboard/local_settings.py
    regexp={{ item.key }}
    line={{ item.value }}
  with_items: "{{ horizon_config }}"
  notify: restart horizon
