---
# file: roles/horizon/tasks/config.yml
- name: Set Horizon configuration
  template:
    src=etc/openstack-dashboard/local_settings.py.j2
    dest=/etc/openstack-dashboard/local_settings.py
  notify: restart horizon

- name: Set Horizon extras configuration
  lineinfile:
    dest=/etc/openstack-dashboard/local_settings.py
    regexp={{ item.key }}
    line={{ item.value }}
  with_items: "{{ horizon_config_extras }}"
  notify: restart horizon

- meta: flush_handlers
