---
# file: roles/horizon/tasks/firewall.yml
- name: Horizon firewalld rule
  firewalld:
    port="{{ item }}/tcp"
    permanent=true
    state=enabled
    immediate=true
  with_items:
    - "{{ horizon_internal_port }}"
    - "{{ horizon_public_port }}"
