---
# file: repo/horizon/tasks/install.yml
- name: Installing packages needed by Horizon
  package:
    name={{ item }}
    state=latest
  with_items: "{{ horizon_packages }}"

- name: Getting Horizon source code
  git:
    repo={{ horizon_git_url }}
    dest={{ working_dir}}/openstack/horizon
    version={{ horizon_version }}

- name: Installing Horizon requirements via pip
  pip:
    virtualenv={{ working_dir }}/virtualenvs/horizon
    requirements={{ working_dir }}/openstack/horizon/requirements.txt

- name: Installing Horizon via setup.py
  shell:
    source {{ working_dir }}/virtualenvs/horizon/bin/activate && \
    cd {{ working_dir }}/openstack/horizon && \
    python setup.py install --record /var/log/horizon/horizon-setup.log
  args:
    executable: /bin/bash

- name: Copying Horizon local_settings.py config file
  copy:
    src={{ working_dir }}/openstack/horizon/openstack_dashboard/local/local_settings.py.example
    dest={{ working_dir }}/virtualenvs/horizon/lib/python2.7/site-packages/openstack_dashboard/local/local_settings.py
    remote_src=yes
    group={{ horizon_group }}
    mode=0640

- name: Linking /etc/openstack-dashboard directory to Horizon virtualenv
  file:
    src={{ working_dir }}/virtualenvs/horizon/lib/python2.7/site-packages/openstack_dashboard/local
    dest=/etc/openstack-dashboard
    state=link

- name: Set the right user permissions to the virtualenv
  file:
    path={{ working_dir }}/virtualenvs/horizon
    owner={{ horizon_uid }}
    group={{ horizon_gid }}
    recurse=yes
