---
# file: roles/horizon/tasks/nginx.yml
- name: Installing uWSGI from pip
  pip:
    name=uwsgi

- name: Mask Nginx service (Debian family)
  command:
    systemctl mask nginx
  when: ansible_os_family == 'Debian'

- name: Installing Nginx HTTP server
  package:
    name=nginx
    state=latest

- name: Adding systemd declaration for uWSGI Horizon
  template:
    src=usr/lib/systemd/system/openstack-dashboard.service.j2
    dest="{{ horizon_systemd_path }}/system/openstack-dashboard.service"
  notify: systemctl reload

- name: Configuring uWSGI for Horizon
  template:
    src=etc/uwsgi.d/horizon/horizon.yml.j2
    dest=/etc/uwsgi.d/horizon/horizon.yml
  notify: restart horizon

- name: Enabling and starting Horizon service
  service:
    name=openstack-dashboard
    state=started
    enabled=yes

- name: Creating Nginx Horizon virtualhost
  template:
    src=etc/nginx/conf.d/10-horizon.conf.j2
    dest="{{ horizon_nginx_configdir }}/10-horizon.conf"
  notify: restart nginx

- name: Cleaning Nginx configuration
  file:
    name={{ item }}
    state=absent
  with_items:
    - "{{ horizon_nginx_configdir }}/default.conf"
    - "{{ horizon_nginx_configdir }}/default"
    - "{{ horizon_nginx_configdir }}/example_ssl.conf"

- name: Unmask Nginx service (Debian family)
  command:
    systemctl unmask nginx
  when: ansible_os_family == 'Debian'

- name: Enabling and starting Nginx service
  service:
    name=nginx
    state=restarted
    enabled=yes

- meta: flush_handlers
