---
# file: roles/horizon/tasks/prepare.yml
- name: Creating Horizon working directories
  file:
    path={{ item }}
    state=directory
    mode=0755
  with_items:
    - /var/log/horizon
    - /etc/uwsgi.d/
    - /etc/uwsgi.d/horizon
    - "{{ working_dir }}"
    - "{{ working_dir }}/openstack"
    - "{{ working_dir }}/virtualenvs/horizon"

- name: Set the correct permissions on Horizon directories
  file:
    path=/var/log/horizon
    owner={{ horizon_user }}
    group={{ horizon_group }}

- name: Adding /etc/logrotate.d/horizon file
  copy:
    src=etc/logrotate.d/horizon
    dest=/etc/logrotate.d/horizon
