---
# file: roles/horizon/tasks/selinux.yml
- name: Labeling SELinux ports for Horizon
  seport:
    ports={{ horizon_port }}
    proto=tcp
    setype=commplex_link_port_t
    state=present

- name: Allowing SELinux booleans for Horizon
  seboolean:
    name={{ item }}
    state=yes
    persistent=yes
  with_items:
    - httpd_can_network_connect
    - httpd_use_openstack

- name: Building and installing SELinux module
  copy:
    src=selinux/horizon.te
    dest=/tmp/

- command:
    /usr/bin/checkmodule -M -m -o /tmp/horizon.mod /tmp/horizon.te
- command:
    /usr/bin/semodule_package -m /tmp/horizon.mod -o /tmp/horizon.pp
- command:
    /usr/sbin/semodule -i /tmp/horizon.pp
